// ---------------------------------------------------------------------------
// Whether they actually wrote back.
//
// A chase only goes out to somebody who has said nothing, so "said nothing" has
// to be exactly right in both directions. Chase a customer who replied on
// Tuesday and you look as though nobody read it; stop chasing because their
// mail server sent a holiday notice and the whole point of the chase is gone.
//
// The hub already answers most of this. Every inbound message carries
// `auto_kind` from lib/threading.ts - 'bounce', 'auto-reply', 'bulk' or
// 'own-notification', or null for something a person typed - worked out from
// the headers at the moment it was collected. So the rule is: an inbound
// message with no auto_kind on it, from one of that contact's addresses, later
// than the last thing we sent them.
//
// This file adds the one case those headers miss. A good many out-of-office
// replies carry no `Auto-Submitted` header at all, particularly from older
// Exchange servers and from phones, and arrive looking exactly like a person
// typing "I am away until the 14th". The subject is the only tell, and it is a
// reliable one, because the phrases are generated by the mail program rather
// than typed by the person.
// ---------------------------------------------------------------------------

/** What mail programs call an out-of-office when they generate one. Anchored at
 *  the start after any Re:/Fwd: prefixes, because "our automatic reply system
 *  is down" is a person writing to us about their problem. */
const OUT_OF_OFFICE = [
  /^(?:re:|fw:|fwd:)?\s*out\s+of\s+(?:the\s+)?office\b/i,
  /^(?:re:|fw:|fwd:)?\s*automatic(?:ally)?\s+reply\b/i,
  /^(?:re:|fw:|fwd:)?\s*auto(?:matic)?[-\s]?response\b/i,
  /^(?:re:|fw:|fwd:)?\s*autoreply\b/i,
  /^(?:re:|fw:|fwd:)?\s*away\s+from\s+(?:my\s+)?(?:the\s+)?(?:office|desk|email)\b/i,
  /^(?:re:|fw:|fwd:)?\s*on\s+annual\s+leave\b/i,
  /^(?:re:|fw:|fwd:)?\s*maternity\s+leave\b/i,
  /^(?:re:|fw:|fwd:)?\s*thank\s+you\s+for\s+(?:your\s+)?(?:email|enquiry|message)[.!]?$/i,
]

/** Whether a subject line is a mail program talking rather than a person. */
export function looksLikeOutOfOffice(subject: string | null | undefined): boolean {
  const value = (subject ?? '').trim()
  if (!value) return false
  return OUT_OF_OFFICE.some((pattern) => pattern.test(value))
}

/**
 * Whether one inbound message counts as a reply for the purposes of standing a
 * chase down.
 *
 * A bounce is emphatically not a reply - it is the address failing, and it is
 * handled as one somewhere else. Neither is a mailing list, an out-of-office,
 * or the site's own notification to itself.
 */
export function isRealReply(message: {
  autoKind: string | null
  subject: string | null
}): boolean {
  if (message.autoKind) return false
  return !looksLikeOutOfOffice(message.subject)
}

/**
 * Whether an inbound message is the mail system saying the address is dead.
 *
 * Only the hard kind is worth acting on here. A full mailbox on Tuesday is a
 * soft bounce and the address is perfectly good on Wednesday, so what this asks
 * is only whether the message is a delivery report at all; how hard the bounce
 * was comes from the mail service's own event where there is one.
 */
export function isBounceNotice(message: { autoKind: string | null }): boolean {
  return message.autoKind === 'bounce'
}

/** The bounce kinds that mean "never write to this address again". A soft
 *  bounce, a deferral or a transient error is a bad afternoon, not a dead
 *  address, and suppressing on one of those loses a customer permanently over a
 *  full mailbox. */
const PERMANENT_BOUNCES: ReadonlySet<string> = new Set(['hard', 'invalid', 'blocked'])

export function isPermanentBounce(bounceKind: string | null | undefined): boolean {
  return !!bounceKind && PERMANENT_BOUNCES.has(bounceKind)
}
