import { nanoid } from 'nanoid'
import { getActiveMediaProvider, isMediaProviderConfigured } from '@/lib/config/env'
import { downloadMedia } from '@/lib/media/upload'
import {
  createOutboundThread,
  defaultInboxIdFor,
  getInbox,
  getQuotableMessage,
  getThread,
  insertOutboundAttachment,
  insertOutboundMessage,
  listInboxes,
  newestMessageOnThread,
  recordAppendOutcome,
  recordLink,
  reopenForRetry,
  settleDelivery,
  getMessage,
  getSettings,
  listAttachmentsForMessage,
  type OutboundMessageRow,
} from './db'
import { loadAttachmentBytes } from './attachments'
import {
  assembleBody,
  buildReferences,
  checkAttachmentBudget,
  forwardSubject,
  generateMessageId,
  outgoingHeaders,
  quoteForForward,
  quoteForReply,
  replyRecipients,
  replySubject,
  type OutgoingAttachment,
  type ReplyMode,
} from './compose'
import { normaliseAddress, isValidAddress } from './addresses'
import { getSiteTimezone } from '@/lib/config/timezone'
import { normaliseSubject, buildSnippet, cleanMessageId } from './threading'
import { htmlToText } from './html'
import { buildRawMessage } from './mime'
import { appendToSent } from './append'
import { chooseSignatureSource, renderInboxSignature } from './signature'
import { deliver, sendingIdentity, transportForInbox, type SendableMessage } from './transport'

// ---------------------------------------------------------------------------
// Sending.
//
// The order of operations is the point of this file, and it is this:
//
//   1. Work out everything that can be refused - recipients, the size of the
//      attachments, whether the inbox exists - and refuse it BEFORE anything
//      has been written or sent. A refusal at this stage costs nothing and the
//      person can fix it and press Send again.
//   2. Write the row, with delivery_status 'sending' and the caller's
//      idempotency key on it. From here on the fact that we tried survives a
//      crash, and a second press of the same button finds this row instead of
//      making another.
//   3. Send.
//   4. Settle the row: 'sent' with whatever the provider called it, or 'failed'
//      with a sentence a person can act on and a retry that reuses this row.
//   5. Copy to the Sent folder, if the inbox asks for it. This one is allowed
//      to fail. The email has gone.
//
// Nothing here fails silently. Every path either returns a message id or
// returns a reason, and the reason is written in English rather than in
// whatever the mail service said.
// ---------------------------------------------------------------------------

export type SendRequest = {
  /** Answering an existing conversation, or starting one. */
  threadId?: string
  /** Required when starting a conversation; taken from the thread otherwise. */
  inboxId?: string
  mode: ReplyMode | 'forward' | 'new'
  /** Overrides the recipients worked out from the conversation. */
  to?: string[]
  cc?: string[]
  subject?: string
  bodyHtml: string
  /** Files already in storage - a media library item, or something just
   *  uploaded. Bytes are fetched here, not trusted from the browser. */
  attachments?: Array<{
    /** Storage key, as the media library holds it. */
    key: string
    url: string
    filename: string
    contentType: string | null
  }>
  /** Carry the attachments of the message being answered or forwarded. */
  includeOriginalAttachments?: boolean
  /** The message being replied to or forwarded, when it is not the newest. */
  inReplyToMessageId?: string
  /** Generated by whoever pressed Send. The same token twice is one email. */
  idempotencyKey: string
  /** Link the new conversation to a record in another module (D12). */
  link?: { moduleName: string; recordType: string; recordId: string; label: string }
  authorUserId: string
}

export type SendResult =
  | { ok: true; messageId: string; threadId: string; alreadySent: boolean }
  | { ok: false; reason: string }

/** Everything the composer needs to know before it is worth sending anything. */
export async function prepareSend(request: SendRequest): Promise<
  | { ok: false; reason: string }
  | {
      ok: true
      inboxId: string
      threadId: string | null
      to: string[]
      cc: string[]
      subject: string
      parent: Awaited<ReturnType<typeof getQuotableMessage>>
    }
> {
  const thread = request.threadId ? await getThread(request.threadId) : null
  if (request.threadId && !thread) {
    return { ok: false, reason: 'That conversation no longer exists.' }
  }

  const inboxId = request.inboxId ?? thread?.inboxId ?? null
  if (!inboxId) {
    return {
      ok: false,
      reason: 'This conversation is not filed in an inbox yet, so there is nothing to send it from. File it first, or pick which address to write from.',
    }
  }
  const inbox = await getInbox(inboxId)
  if (!inbox) return { ok: false, reason: 'That inbox no longer exists.' }

  const parent = request.inReplyToMessageId
    ? await getQuotableMessage(request.inReplyToMessageId)
    : thread
      ? await newestMessageOnThread(thread.id)
      : null

  const inboxes = await listInboxes()
  const ownAddresses = inboxes.map((i) => i.address)

  let to = (request.to ?? []).map(normaliseAddress).filter(Boolean)
  let cc = (request.cc ?? []).map(normaliseAddress).filter(Boolean)

  if (to.length === 0 && parent && (request.mode === 'reply' || request.mode === 'reply-all')) {
    const worked = replyRecipients(
      {
        fromAddress: parent.fromAddress,
        replyTo: parent.replyTo,
        toAddresses: parent.toAddresses,
        ccAddresses: parent.ccAddresses,
      },
      request.mode,
      ownAddresses,
    )
    to = worked.to
    cc = worked.cc
  }

  if (to.length === 0) {
    return { ok: false, reason: 'There is nobody to send this to. Add an address.' }
  }
  const bad = [...to, ...cc].find((address) => !isValidAddress(address))
  if (bad) return { ok: false, reason: `"${bad}" does not look like an email address.` }

  const subject =
    request.subject?.trim() ||
    (request.mode === 'forward'
      ? forwardSubject(parent?.subject ?? thread?.subject ?? null)
      : request.mode === 'new'
        ? ''
        : replySubject(parent?.subject ?? thread?.subject ?? null))

  if (!subject) return { ok: false, reason: 'Give the message a subject.' }

  return { ok: true, inboxId, threadId: thread?.id ?? null, to, cc, subject, parent }
}

/**
 * Sends a message.
 *
 * Access is NOT checked here - the route does it, because the route is the one
 * holding the session. This function assumes the caller has already established
 * that this person may reply from this inbox.
 */
export async function sendMessage(request: SendRequest): Promise<SendResult> {
  const prepared = await prepareSend(request)
  if (!prepared.ok) return prepared

  const inbox = await getInbox(prepared.inboxId)
  if (!inbox) return { ok: false, reason: 'That inbox no longer exists.' }

  const parent = prepared.parent
  // The quoted original carries a time the recipient will read, so it is stamped
  // in the site's own zone rather than the server's.
  const timezone = await getSiteTimezone()
  const quoted =
    request.mode === 'forward' && parent
      ? quoteForForward({
          sentAt: parent.sentAt,
          fromName: parent.fromName,
          fromAddress: parent.fromAddress,
          toAddresses: parent.toAddresses,
          subject: parent.subject,
          bodyText: parent.bodyText,
          bodyHtml: parent.bodyHtml,
        }, timezone)
      : parent && (request.mode === 'reply' || request.mode === 'reply-all')
        ? quoteForReply({
            sentAt: parent.sentAt,
            fromName: parent.fromName,
            fromAddress: parent.fromAddress,
            toAddresses: parent.toAddresses,
            subject: parent.subject,
            bodyText: parent.bodyText,
            bodyHtml: parent.bodyHtml,
          }, timezone)
        : null

  // Whoever pressed Send may have an address of their own, and its signature is
  // theirs wherever they are answering from. One extra read per send, and only
  // a second one when they actually have one.
  const ownInboxId = await defaultInboxIdFor(request.authorUserId)
  const ownInbox = ownInboxId && ownInboxId !== inbox.id ? await getInbox(ownInboxId) : null

  const body = assembleBody({
    bodyHtml: request.bodyHtml,
    // Rendered rather than read: the inbox's signature may be rich text, pasted
    // markup or a stack of email blocks, and only one place knows how to turn
    // each of those into an email.
    signature: await renderInboxSignature(chooseSignatureSource(ownInbox, inbox)),
    quoted,
  })

  // Everything that travels, gathered before anything is written. Bytes come
  // from storage rather than from the browser: a filename and a size in a
  // request body are a claim, and an attachment is not sent on a claim.
  const files = await gatherAttachments(request, parent?.id ?? null)
  if (!files.ok) return { ok: false, reason: files.reason }

  const budget = checkAttachmentBudget(
    files.items.map(
      (f): OutgoingAttachment => ({
        filename: f.filename,
        contentType: f.contentType,
        sizeBytes: f.content.byteLength,
      }),
    ),
    Buffer.byteLength(body.html) + Buffer.byteLength(body.text),
  )
  if (!budget.ok) return { ok: false, reason: budget.reason }

  // --- everything above this line can still be refused for free -------------

  const identity = sendingIdentity(inbox)
  const messageIdHeaderValue = generateMessageId(inbox.address)
  const references = parent
    ? buildReferences({ messageIdHeader: parent.messageIdHeader, references: parent.references })
    : []

  const threadId =
    prepared.threadId ??
    (await createOutboundThread({
      inboxId: prepared.inboxId,
      subject: prepared.subject,
      subjectNormalised: normaliseSubject(prepared.subject),
      preview: buildSnippet(body.text),
    }))

  const { row, created } = await insertOutboundMessage({
    threadId,
    inboxId: prepared.inboxId,
    idempotencyKey: request.idempotencyKey,
    messageIdHeader: messageIdHeaderValue,
    inReplyTo: parent?.messageIdHeader ?? null,
    references,
    fromName: identity.name,
    fromAddress: identity.address,
    toAddresses: prepared.to,
    ccAddresses: prepared.cc,
    subject: prepared.subject,
    bodyText: body.text,
    bodyHtml: body.html,
    snippet: buildSnippet(body.text),
    hasAttachments: files.items.length > 0,
    sizeBytes: budget.totalBytes,
    authorUserId: request.authorUserId,
  })

  if (!created) {
    // The same Send, pressed twice or retried after an ambiguous timeout. The
    // first one owns this message; do not send a second copy of it (E14).
    return { ok: true, messageId: row.id, threadId: row.threadId, alreadySent: true }
  }

  for (const file of files.items) {
    await insertOutboundAttachment({
      messageId: row.id,
      filename: file.filename,
      contentType: file.contentType,
      sizeBytes: file.content.byteLength,
      mediaKey: file.key,
      mediaProvider: file.provider,
      mediaUrl: file.url,
    })
  }

  if (request.link) {
    await recordLink({
      threadId,
      personId: null,
      moduleName: request.link.moduleName,
      recordType: request.link.recordType,
      recordId: request.link.recordId,
      label: request.link.label,
      confidence: 100,
      linkedBy: 'user',
    })
  }

  const sendable: SendableMessage = {
    to: prepared.to,
    cc: prepared.cc,
    from: identity,
    transport: await transportForInbox(inbox),
    replyTo: inbox.address,
    subject: prepared.subject,
    html: body.html,
    text: body.text,
    headers: outgoingHeaders({
      messageId: messageIdHeaderValue,
      inReplyTo: parent?.messageIdHeader ?? null,
      references,
      // Both off unless the site has said otherwise. The tracking tag is only
      // any use on Brevo - it is Brevo that hands it back on its events - and
      // putting it on a message going out through somebody's own mail server
      // would be a header that means nothing travelling to a stranger.
      ...(await receiptHeaderOptions(inbox.sendTransport, inbox.address, row.id)),
    }),
    attachments: files.items.map((f) => ({
      filename: f.filename,
      contentType: f.contentType,
      content: f.content,
    })),
  }

  const outcome = await deliver(sendable)

  if (!outcome.ok) {
    await settleDelivery(row.id, { status: 'failed', error: outcome.error })
    return { ok: false, reason: outcome.error }
  }

  await settleDelivery(row.id, {
    status: 'sent',
    // Cleaned, because an inbound In-Reply-To is cleaned too and the two have
    // to compare equal if a reply quoting the provider's id is to find its
    // thread again.
    providerMessageId: cleanMessageId(outcome.providerMessageId),
  })

  await copyToSentFolder({
    messageId: row.id,
    inbox,
    identity,
    sendable,
    sentAt: new Date(),
  })

  return { ok: true, messageId: row.id, threadId, alreadySent: false }
}

/**
 * The copy in the owner's own Sent folder (D4).
 *
 * Every failure in here is recorded on the message and swallowed. The email has
 * already gone; a failed copy means the owner's phone is missing a duplicate,
 * and reporting that as a failed send would be a lie that stops people trusting
 * the screen.
 */
async function copyToSentFolder(input: {
  messageId: string
  inbox: { appendToSent: boolean; connectionId: string | null; sentFolder: string | null }
  identity: { name: string | null; address: string }
  sendable: SendableMessage
  sentAt: Date
}): Promise<void> {
  if (!input.inbox.appendToSent || !input.inbox.connectionId) {
    await noteAppend(input.messageId, { status: 'skipped' })
    return
  }

  try {
    const raw = await buildRawMessage({
      from: input.identity,
      to: input.sendable.to,
      cc: input.sendable.cc,
      replyTo: input.sendable.replyTo,
      subject: input.sendable.subject,
      html: input.sendable.html,
      text: input.sendable.text,
      // Our own Message-ID goes on the copy, which is what makes the sync
      // engine recognise it as ours when it next reads Sent rather than filing
      // it as a newly discovered email (E11).
      headers: input.sendable.headers,
      attachments: input.sendable.attachments.map((f) => ({
        filename: f.filename,
        contentType: f.contentType,
        sizeBytes: f.content.byteLength,
        content: f.content,
      })),
      sentAt: input.sentAt,
    })

    const result = await appendToSent({
      connectionId: input.inbox.connectionId,
      sentFolder: input.inbox.sentFolder,
      raw,
      sentAt: input.sentAt,
    })

    await noteAppend(
      input.messageId,
      result.ok
        ? { status: 'appended', folder: result.folder, uid: result.uid }
        : { status: 'failed', error: result.reason },
    )
  } catch (err) {
    await noteAppend(input.messageId, {
      status: 'failed',
      error: err instanceof Error ? err.message : String(err),
    })
  }
}

/** Recording what happened to the copy must never be the thing that takes a
 *  successful send down, so even the recording is allowed to fail. */
async function noteAppend(
  messageId: string,
  outcome: Parameters<typeof recordAppendOutcome>[1],
): Promise<void> {
  try {
    await recordAppendOutcome(messageId, outcome)
  } catch (err) {
    console.error('[unified-inbox] could not record the Sent-folder copy outcome', err)
  }
}

type GatheredAttachment = {
  filename: string
  contentType: string | null
  content: Buffer
  /** Where the bytes live, so a retry does not have to go and find them again.
   *  Null for something carried out of an inbound message that has not been
   *  cached yet. */
  key: string | null
  provider: string | null
  url: string | null
}

/** The bytes for everything travelling with this message. */
async function gatherAttachments(
  request: SendRequest,
  parentMessageId: string | null,
): Promise<{ ok: true; items: GatheredAttachment[] } | { ok: false; reason: string }> {
  const items: GatheredAttachment[] = []

  const provider = (request.attachments ?? []).length ? await getActiveMediaProvider() : null
  if ((request.attachments ?? []).length && (!provider || !isMediaProviderConfigured(provider))) {
    return {
      ok: false,
      reason: 'This site has no file storage set up, so attachments cannot be sent yet.',
    }
  }

  for (const file of request.attachments ?? []) {
    try {
      const bytes = await downloadMedia(provider!, file.key, file.url)
      items.push({
        filename: file.filename,
        contentType: file.contentType,
        content: Buffer.from(bytes),
        key: file.key,
        provider,
        url: file.url,
      })
    } catch {
      return {
        ok: false,
        reason: `"${file.filename}" could not be read from storage, so nothing has been sent. Try attaching it again.`,
      }
    }
  }

  // A forward that loses the attachments is not a forward - the attachment is
  // usually the entire reason somebody is forwarding it.
  if (request.includeOriginalAttachments && parentMessageId) {
    const originals = await listAttachmentsForMessage(parentMessageId)
    for (const attachment of originals) {
      const fetched = await loadAttachmentBytes(attachment.id)
      if (!fetched.ok) {
        return {
          ok: false,
          reason: `"${attachment.filename}" could not be fetched from the mail server, so nothing has been sent. ${fetched.reason}`,
        }
      }
      items.push({
        filename: fetched.filename,
        contentType: fetched.contentType,
        content: fetched.buffer,
        key: attachment.mediaKey,
        provider: attachment.mediaProvider,
        url: attachment.mediaUrl,
      })
    }
  }

  return { ok: true, items }
}

/**
 * Tries a failed message again, reusing its row.
 *
 * Reusing the row is what keeps the thread honest: a retry is the same message
 * having another go, not a second message that happens to say the same thing.
 * Only a message that actually failed can be retried - one still in 'sending'
 * may yet be in flight, and racing it would put two copies in front of the
 * customer.
 */
export async function retrySend(messageId: string): Promise<SendResult> {
  const message = await getMessage(messageId)
  const quotable = await getQuotableMessage(messageId)
  if (!message || !quotable) return { ok: false, reason: 'That message no longer exists.' }
  if (message.direction !== 'out') return { ok: false, reason: 'That is not a message we sent.' }
  if (message.deliveryStatus === 'sent') {
    return { ok: true, messageId: message.id, threadId: message.threadId, alreadySent: true }
  }
  if (!(await reopenForRetry(messageId))) {
    return {
      ok: false,
      reason: 'That message is being sent right now. Give it a moment before trying again.',
    }
  }

  const inbox = message.inboxId ? await getInbox(message.inboxId) : null
  if (!inbox) {
    await settleDelivery(messageId, {
      status: 'failed',
      error: 'The inbox this was written from no longer exists.',
    })
    return { ok: false, reason: 'The inbox this was written from no longer exists.' }
  }

  const stored = await listAttachmentsForMessage(messageId)
  const files: SendableMessage['attachments'] = []
  for (const attachment of stored) {
    const fetched = await loadAttachmentBytes(attachment.id)
    if (!fetched.ok) {
      const reason = `"${attachment.filename}" could not be read, so nothing has been sent again. ${fetched.reason}`
      await settleDelivery(messageId, { status: 'failed', error: reason })
      return { ok: false, reason }
    }
    files.push({
      filename: fetched.filename,
      contentType: fetched.contentType,
      content: fetched.buffer,
    })
  }

  const identity = sendingIdentity(inbox)
  const sendable: SendableMessage = {
    to: message.toAddresses,
    cc: message.ccAddresses,
    from: identity,
    transport: await transportForInbox(inbox),
    replyTo: inbox.address,
    subject: message.subject ?? '(no subject)',
    html: message.bodyHtml ?? '',
    text: message.bodyText ?? htmlToText(message.bodyHtml ?? ''),
    headers: outgoingHeaders({
      // The SAME Message-ID as the first attempt. A retry that minted a new one
      // would arrive as a second, unrelated email in the customer's client if
      // the first one turned out to have gone after all.
      messageId: message.messageIdHeader ?? generateMessageId(inbox.address),
      inReplyTo: quotable.messageIdHeader && quotable.references.length
        ? quotable.references[quotable.references.length - 1]!
        : null,
      references: quotable.references,
      // The same row id as the first attempt, for the same reason: whichever
      // attempt actually lands, its events belong to this one message.
      ...(await receiptHeaderOptions(inbox.sendTransport, inbox.address, messageId)),
    }),
    attachments: files,
  }

  const outcome = await deliver(sendable)
  if (!outcome.ok) {
    await settleDelivery(messageId, { status: 'failed', error: outcome.error })
    return { ok: false, reason: outcome.error }
  }

  await settleDelivery(messageId, {
    status: 'sent',
    providerMessageId: cleanMessageId(outcome.providerMessageId),
  })
  await copyToSentFolder({ messageId, inbox, identity, sendable, sentAt: new Date() })

  return { ok: true, messageId, threadId: message.threadId, alreadySent: false }
}

/**
 * The two receipt headers, or nothing at all.
 *
 * Read from the settings on every send rather than passed in, because the
 * answer can change between one reply and the next and a stale copy would mean
 * a site that switched tracking off yesterday is still tracking today.
 */
async function receiptHeaderOptions(
  sendTransport: string,
  inboxAddress: string,
  messageRowId: string,
): Promise<{ trackingTag?: string; readReceiptTo?: string }> {
  const settings = await getSettings()
  return {
    ...(settings.trackOpens && sendTransport === 'brevo' ? { trackingTag: messageRowId } : {}),
    ...(settings.requestReadReceipts ? { readReceiptTo: inboxAddress } : {}),
  }
}

/** A token for one press of Send, for callers that have not got one. */
export function newIdempotencyKey(): string {
  return nanoid(24)
}

export type { OutboundMessageRow }
