import { z } from 'zod'

// Shared between the create and the edit route, so an inbox cannot be saved
// through one of them with a field the other would have refused.

export const InboxBody = z.object({
  name: z.string().min(1).max(120),
  address: z.string().min(3).max(255),
  connectionId: z.string().nullable().optional(),
  imapFolder: z.string().min(1).max(255).optional(),
  sentFolder: z.string().max(255).nullable().optional(),
  isCatchAll: z.boolean().optional(),
  sendTransport: z.enum(['brevo', 'smtp']).optional(),
  brevoApiKey: z.string().nullable().optional(),
  smtpHost: z.string().max(255).nullable().optional(),
  smtpPort: z.number().int().min(1).max(65535).nullable().optional(),
  smtpUsername: z.string().max(255).nullable().optional(),
  smtpPassword: z.string().nullable().optional(),
  fromName: z.string().max(120).nullable().optional(),
  // All three signature kinds are sent on every save, not only the active one:
  // switching kind in the editor must not throw the other two away.
  signatureKind: z.enum(['markdown', 'html', 'puck']).optional(),
  signature: z.string().max(5000).nullable().optional(),
  signatureHtml: z.string().max(50000).nullable().optional(),
  signaturePuck: z.unknown().nullable().optional(),
  appendToSent: z.boolean().optional(),
  colour: z.string().max(32).nullable().optional(),
  sortOrder: z.number().int().min(0).max(9999).optional(),
})

export const InboxPatchBody = InboxBody.partial()

/** The order of the addresses: every inbox id, once, in the order they should appear.
 *  Capped well above any plausible number of addresses so a runaway list is a
 *  refusal rather than a very long UPDATE. */
export const InboxOrderBody = z.object({
  ids: z.array(z.string().min(1)).min(1).max(200),
})

/** What the composer posts to send a message. Deliberately strict: an
 *  attachment is described by where it already lives in storage, never by
 *  bytes in the request, so nothing can be talked into emailing an arbitrary
 *  file by asking nicely. */
export const SendBody = z.object({
  threadId: z.string().min(1).optional(),
  inboxId: z.string().min(1).optional(),
  mode: z.enum(['reply', 'reply-all', 'forward', 'new']),
  to: z.array(z.string().min(1)).max(50).optional(),
  cc: z.array(z.string().min(1)).max(50).optional(),
  subject: z.string().max(500).optional(),
  bodyHtml: z.string().max(500_000),
  attachments: z
    .array(
      z.object({
        key: z.string().min(1),
        url: z.string().min(1),
        filename: z.string().min(1).max(255),
        contentType: z.string().max(200).nullable().default(null),
      }),
    )
    .max(20)
    .optional(),
  includeOriginalAttachments: z.boolean().optional(),
  inReplyToMessageId: z.string().min(1).optional(),
  // Generated by whoever pressed Send. Two requests carrying the same one are
  // the same press, and the second sends nothing (E14).
  idempotencyKey: z.string().min(8).max(100),
  /** The draft this was written in, if it was written in one. Thrown away once
   *  the message has actually gone - a draft that outlives its own send is the
   *  reply somebody sends a second time next week. */
  draftId: z.string().min(1).optional(),
  link: z
    .object({
      moduleName: z.string().min(1).max(100),
      recordType: z.string().min(1).max(100),
      recordId: z.string().min(1).max(200),
      label: z.string().min(1).max(300),
    })
    .optional(),
})

/** The files travelling with a message, described by where they already live
 *  in storage. Shared by the send and the draft routes so a draft cannot hold
 *  an attachment the send route would then refuse. */
const AttachmentRef = z.object({
  key: z.string().min(1),
  url: z.string().min(1),
  filename: z.string().min(1).max(255),
  contentType: z.string().max(200).nullable().default(null),
  sizeBytes: z.number().int().min(0).nullable().default(null),
})

/** What either composer posts to put a message down half-written. `id` is
 *  present from the second save onwards, so pressing Save four times leaves one
 *  draft rather than four. */
export const DraftBody = z.object({
  id: z.string().min(1).optional(),
  threadId: z.string().min(1).nullable().optional(),
  inboxId: z.string().min(1).nullable().optional(),
  mode: z.enum(['new', 'reply', 'reply-all', 'forward']).default('new'),
  to: z.array(z.string().min(1)).max(50).optional(),
  cc: z.array(z.string().min(1)).max(50).optional(),
  subject: z.string().max(500).nullable().optional(),
  /** As typed, not as HTML: what goes back into the box has to be what came
   *  out of it. */
  body: z.string().max(500_000),
  attachments: z.array(AttachmentRef).max(20).optional(),
  /** When it should go out on its own, as the wall clock somebody typed:
   *  "2026-09-04T09:00", with no zone on it. It is turned into an instant on
   *  the server against the SITE's zone - see lib/scheduled.ts - because nine
   *  o'clock means nine o'clock to the person reading the screen, not to
   *  whichever machine happens to be answering. Null takes the time back off
   *  and leaves an ordinary draft. */
  sendAt: z.string().max(40).nullable().optional(),
})

/** What the reading screen posts when somebody works through a conversation.
 *  Every field is optional and any combination is legal, because "mark it done
 *  and hand it to Marcus" is one press of one button. */
export const ThreadPatchBody = z.object({
  unread: z.boolean().optional(),
  status: z.enum(['open', 'snoozed', 'done']).optional(),
  /** An ISO stamp. Only read when the status is 'snoozed'. */
  snoozeUntil: z.string().datetime().nullable().optional(),
  /** A user id, or null to hand it back to nobody in particular. */
  assigneeUserId: z.string().min(1).nullable().optional(),
})

/** An internal note. `mentions` carries user ids chosen from the list rather
 *  than names scraped out of the text: a colleague called Sam Smith and another
 *  called Sam Smyth are not something a regular expression should be deciding
 *  between. */
export const NoteBody = z.object({
  text: z.string().min(1).max(20_000),
  mentions: z.array(z.string().min(1)).max(20).optional(),
})
